# Copyright (c) 2026, Agilasoft and contributors

from __future__ import annotations

import unittest

from logistics.bir_cas.header_rows import build_cas_header_rows


class TestBuildCasHeaderRows(unittest.TestCase):
	def test_includes_address_and_generator_fields(self):
		context = {
			"company_name": "ALL TRANSPORT NETWORK, INC.",
			"company_address": "Unit 126B, Charlie Bldg.",
			"tin": "000-414-368-00000",
			"report_title": "Sales Book",
			"period_label": "01-01-2026 TO 09-28-2026",
			"generated_by": "Willy Morales",
			"generated_at": "09-28-2026 10:00:00",
		}
		rows = build_cas_header_rows(context)
		flat = [r[0] for r in rows if r]
		self.assertIn("COMPANY: ALL TRANSPORT NETWORK, INC.", flat)
		self.assertIn("ADDRESS: Unit 126B, Charlie Bldg.", flat)
		self.assertIn("TIN: 000-414-368-00000", flat)
		self.assertIn("REPORT: SALES BOOK", flat)
		self.assertIn("PERIOD: 01-01-2026 TO 09-28-2026", flat)
		self.assertIn("GENERATED BY: Willy Morales", flat)
		self.assertIn("DATE AND TIME GENERATED: 09-28-2026 10:00:00", flat)


class TestLegacyHeaderRowCount(unittest.TestCase):
	def test_full_header_has_seven_metadata_rows_before_blank(self):
		context = {
			"company_name": "ALL TRANSPORT NETWORK, INC.",
			"company_address": "Unit 126B, Charlie Bldg.",
			"tin": "000-414-368-00000",
			"report_title": "Sales Book",
			"period_label": "01-01-2026 TO 09-28-2026",
			"generated_by": "Willy Morales",
			"generated_at": "09-28-2026 10:00:00",
		}
		rows = build_cas_header_rows(context)
		self.assertEqual(len(rows), 8)
		self.assertEqual(rows[-1], [])


if __name__ == "__main__":
	unittest.main()
