# Copyright (c) 2026, Agilasoft and contributors

from __future__ import annotations

import io
from typing import Iterable

from openpyxl import load_workbook
from openpyxl.workbook import Workbook

from logistics.bir_cas.company_info import get_cas_header_context
from logistics.bir_cas.header_rows import build_cas_header_rows


def prepend_cas_header_to_row_matrix(
	row_matrix: list[list],
	*,
	company: str | None = None,
	report_title: str,
	period_label: str | None = None,
	filters=None,
) -> list[list]:
	context = get_cas_header_context(
		company=company,
		report_title=report_title,
		period_label=period_label,
		filters=filters,
	)
	return build_cas_header_rows(context) + list(row_matrix)


def _parse_label_row(cell_value) -> tuple[str, str] | None:
	if cell_value is None:
		return None
	text = str(cell_value).strip()
	if ":" not in text:
		return None
	label, _, value = text.partition(":")
	return label.strip().upper(), value.strip()


def _scan_existing_header(sheet) -> dict[str, str]:
	found: dict[str, str] = {}
	for row in sheet.iter_rows(max_row=15, max_col=1, values_only=True):
		parsed = _parse_label_row(row[0] if row else None)
		if parsed:
			found[parsed[0]] = parsed[1]
	return found


def _merge_header_context(existing: dict[str, str], context: dict[str, str]) -> dict[str, str]:
	merged = dict(context)
	for key in ("COMPANY", "ADDRESS", "TIN", "REPORT", "PERIOD", "GENERATED BY", "DATE AND TIME GENERATED"):
		if existing.get(key):
			field_map = {
				"COMPANY": "company_name",
				"ADDRESS": "company_address",
				"TIN": "tin",
				"REPORT": "report_title",
				"PERIOD": "period_label",
				"GENERATED BY": "generated_by",
				"DATE AND TIME GENERATED": "generated_at",
			}
			if key == "REPORT":
				merged[field_map[key]] = existing[key]
			else:
				merged[field_map[key]] = existing[key]
	return merged


def _write_header_block(sheet, header_rows: list[list], data_start_row: int) -> None:
	if data_start_row > 1:
		sheet.insert_rows(1, amount=data_start_row - 1)
	for idx, row in enumerate(header_rows, start=1):
		if row:
			sheet.cell(row=idx, column=1, value=row[0])


def ensure_bir_cas_excel_header(
	xlsx_bytes: bytes,
	*,
	company: str | None = None,
	report_title: str,
	period_label: str | None = None,
	filters=None,
) -> bytes:
	"""Ensure CAS Excel exports include BIR-required header metadata."""
	context = get_cas_header_context(
		company=company,
		report_title=report_title,
		period_label=period_label,
		filters=filters,
	)

	workbook = load_workbook(io.BytesIO(xlsx_bytes))
	sheet = workbook.active

	existing = _scan_existing_header(sheet)
	if existing:
		merged = _merge_header_context(existing, context)
		header_rows = build_cas_header_rows(merged)
		# Drop legacy rows until first blank row or first row that looks like column headers.
		data_start = 1
		for idx, row in enumerate(sheet.iter_rows(max_row=20, values_only=True), start=1):
			if not row or not row[0]:
				data_start = idx + 1
				break
			parsed = _parse_label_row(row[0])
			if not parsed:
				data_start = idx
				break
		else:
			data_start = len(header_rows) + 1

		if data_start > 1:
			sheet.delete_rows(1, data_start - 1)
		_write_header_block(sheet, header_rows, len(header_rows) + 1)
	else:
		header_rows = build_cas_header_rows(context)
		sheet.insert_rows(1, amount=len(header_rows))
		for idx, row in enumerate(header_rows, start=1):
			if row:
				sheet.cell(row=idx, column=1, value=row[0])

	out = io.BytesIO()
	workbook.save(out)
	return out.getvalue()


def write_cas_workbook(
	row_matrix: Iterable[list],
	*,
	company: str | None = None,
	report_title: str,
	period_label: str | None = None,
	filters=None,
	sheet_name: str = "Sheet1",
) -> bytes:
	"""Build a new CAS Excel file with standard header rows."""
	matrix = prepend_cas_header_to_row_matrix(
		list(row_matrix),
		company=company,
		report_title=report_title,
		period_label=period_label,
		filters=filters,
	)
	wb = Workbook()
	ws = wb.active
	ws.title = sheet_name[:31]
	for r_idx, row in enumerate(matrix, start=1):
		for c_idx, value in enumerate(row, start=1):
			ws.cell(row=r_idx, column=c_idx, value=value)
	out = io.BytesIO()
	wb.save(out)
	return out.getvalue()
