# Copyright (c) 2026, Agilasoft and contributors

from __future__ import annotations


def _label_value(label: str, value: str) -> list:
	return [f"{label}: {value}" if value else f"{label}:"]


def build_cas_header_rows(context: dict[str, str]) -> list[list]:
	"""Return BIR CAS metadata rows to prepend above report column headers."""
	rows: list[list] = []
	rows.append(_label_value("COMPANY", context.get("company_name", "")))
	rows.append(_label_value("ADDRESS", context.get("company_address", "")))
	rows.append(_label_value("TIN", context.get("tin", "")))
	report_title = (context.get("report_title") or "").upper()
	rows.append(_label_value("REPORT", report_title))
	if context.get("period_label"):
		rows.append(_label_value("PERIOD", context["period_label"]))
	rows.append(_label_value("GENERATED BY", context.get("generated_by", "")))
	rows.append(_label_value("DATE AND TIME GENERATED", context.get("generated_at", "")))
	rows.append([])
	return rows
