# Copyright (c) 2026, Agilasoft and contributors

from __future__ import annotations

CAS_GENERAL_LEDGER_REPORT = "CAS General Ledger"
GL_TRANSACTION_REPORT_TITLE = "General Ledger Transaction Report"
JOURNAL_BOOK_REPORT = "Journal Book"
CASH_RECEIPTS_BOOK_REPORT = "Cash Receipts Book"
SALES_BOOK_REPORT = "Sales Book"
SALES_BOOK_REPORT_NAMES = {
	SALES_BOOK_REPORT.lower(),
	"bir sales book",
	"subsidiary sales book",
}
PURCHASE_BOOK_REPORT = "Purchase Book"
PURCHASES_BOOK_REPORT_NAMES = {
	"purchases book",
	PURCHASE_BOOK_REPORT.lower(),
	"subsidiary purchases book",
	"bir purchases book",
}


def is_cas_general_ledger(report_title: str | None) -> bool:
	name = (report_title or "").strip().lower()
	return name in {
		CAS_GENERAL_LEDGER_REPORT.lower(),
		GL_TRANSACTION_REPORT_TITLE.lower(),
	}


def is_journal_book(report_title: str | None) -> bool:
	return (report_title or "").strip().lower() == JOURNAL_BOOK_REPORT.lower()


def is_cash_receipts_book(report_title: str | None) -> bool:
	return (report_title or "").strip().lower() == CASH_RECEIPTS_BOOK_REPORT.lower()


def is_sales_book(report_title: str | None) -> bool:
	return (report_title or "").strip().lower() in SALES_BOOK_REPORT_NAMES


def is_purchases_book(report_title: str | None) -> bool:
	return (report_title or "").strip().lower() in PURCHASES_BOOK_REPORT_NAMES


def _label_value(label: str, value: str) -> list:
	return [f"{label}: {value}" if value else f"{label}:"]


def build_cas_header_rows(context: dict[str, str]) -> list[list]:
	"""Return BIR CAS metadata rows to prepend above report column headers."""
	rows: list[list] = []
	rows.append(_label_value("COMPANY", context.get("company_name", "")))
	rows.append(_label_value("ADDRESS", context.get("company_address", "")))
	rows.append(_label_value("TIN", context.get("tin", "")))
	report_title = (context.get("report_title") or "").upper()
	rows.append(_label_value("REPORT", report_title))
	if context.get("period_label"):
		rows.append(_label_value("PERIOD", context["period_label"]))
	rows.append(_label_value("GENERATED BY", context.get("generated_by", "")))
	rows.append(_label_value("DATE AND TIME GENERATED", context.get("generated_at", "")))
	rows.append([])
	return rows


def build_company_letterhead_rows(context: dict[str, str], report_title: str) -> list[list]:
	"""Centered company letterhead: name, address, VAT, title, period, and printed-by."""
	tin = (context.get("tin") or "").strip()
	period = (context.get("period_label") or "").strip()
	printed_by = (context.get("generated_by") or "").strip()
	printed_at = (context.get("printed_at") or "").strip()
	printed_line = f"Printed by {printed_by} {printed_at}".strip()
	return [
		[context.get("company_name") or ""],
		[context.get("company_address") or ""],
		[f"VAT REG. TIN {tin}".strip()],
		[report_title],
		[f"Period: {period}" if period else "Period:"],
		[printed_line],
		[],
	]


def build_gl_letterhead_rows(context: dict[str, str]) -> list[list]:
	"""Centered company letterhead used by the CAS General Ledger Excel export."""
	return build_company_letterhead_rows(context, GL_TRANSACTION_REPORT_TITLE)


def build_journal_book_letterhead_rows(context: dict[str, str]) -> list[list]:
	"""Centered company letterhead used by the Journal Book Excel export."""
	return build_company_letterhead_rows(context, JOURNAL_BOOK_REPORT)


def build_cash_receipts_book_letterhead_rows(context: dict[str, str]) -> list[list]:
	"""Centered company letterhead used by the Cash Receipts Book Excel export."""
	tin = (context.get("tin") or "").strip()
	period = (context.get("period_label") or "").strip()
	printed_by = (context.get("generated_by") or "").strip()
	printed_at = (context.get("printed_at_ampm") or context.get("printed_at") or "").strip()
	printed_line = f"Printed by {printed_by} {printed_at}".strip()
	return [
		[context.get("company_name") or ""],
		[context.get("company_address") or ""],
		[f"VAT REG. TIN {tin}".strip()],
		[CASH_RECEIPTS_BOOK_REPORT],
		[period],
		[printed_line],
		[],
	]


def build_sales_book_letterhead_rows(context: dict[str, str]) -> list[list]:
	"""Centered company letterhead used by the Sales Book Excel export."""
	return build_company_letterhead_rows(context, SALES_BOOK_REPORT)


def build_purchases_book_letterhead_rows(context: dict[str, str]) -> list[list]:
	"""Company letterhead used by the Purchases Book Excel export."""
	tin = (context.get("tin") or "").strip()
	period = (context.get("period_label") or "").strip()
	printed_by = (context.get("generated_by") or "").strip()
	printed_at = (context.get("printed_at") or "").strip()
	printed_line = f"Printed by {printed_by} {printed_at}".strip()
	return [
		[context.get("company_name") or ""],
		[context.get("company_address") or ""],
		[f"VAT REG. TIN {tin}".strip()],
		[PURCHASE_BOOK_REPORT],
		[period],
		[printed_line],
		[],
	]
