# Copyright (c) 2026, www.agilasoft.com and contributors
# For license information, please see license.txt

"""Final document-event handlers for the logistics app.

hooks.py used to append these with import-time loops. The dictionary below is
that result: handler order within each event is the order Frappe runs them.
The credit print-permission patch still runs from hooks.py.
"""

DOC_EVENTS = {'Opportunity': {'onload': 'logistics.pricing_center.utils.opportunity_scopes.on_opportunity_onload',
                 'validate': 'logistics.pricing_center.utils.opportunity_scopes.on_opportunity_validate'},
 'Lead': {'onload': 'logistics.pricing_center.crm_sales_quote_onload.lead_onload'},
 'Prospect': {'onload': 'logistics.pricing_center.crm_sales_quote_onload.prospect_onload',
              'validate': 'logistics.pricing_center.lead_prospect.populate_annual_revenue_from_leads'},
 'Customer': {'validate': 'logistics.utils.party_code.validate_customer_supplier_party_code'},
 'Supplier': {'validate': 'logistics.utils.party_code.validate_customer_supplier_party_code'},
 'Address': {'validate': ['logistics.transport.address_windows.validate_address_window_schedule',
                          'logistics.transport.address_eza.validate_address_eza']},
 'Accounting Dimension': {'after_insert': 'logistics.job_management.gl_item_dimension.on_accounting_dimension_changed',
                          'on_update': 'logistics.job_management.gl_item_dimension.on_accounting_dimension_changed',
                          'on_trash': 'logistics.job_management.gl_item_dimension.on_accounting_dimension_changed'},
 'Cost Center': {'validate': 'logistics.job_management.cost_center_defaults.set_cost_center_branch_default'},
 'Branch': {'before_insert': 'logistics.job_management.cost_center_defaults.set_branch_document_name'},
 'Account': {'validate': 'logistics.logistics.account_job_profit.validate_account_job_profit'},
 'Purchase Invoice': {'validate': ['logistics.invoice_integration.container_deposit_pi.apply_container_deposit_expense_account',
                                   'logistics.invoice_integration.container_deposit_dimensions.sync_container_deposit_pi_accounting_dimensions',
                                   'logistics.invoice_integration.job_number_dimension_sync.sync_job_number_dimension_on_purchase_invoice_items',
                                   'logistics.invoice_integration.gl_item_dimension_sync.sync_item_accounting_dimension_from_invoice_items'],
                      'before_submit': ['logistics.invoice_integration.container_deposit_pi.apply_container_deposit_expense_account',
                                        'logistics.invoice_integration.container_deposit_dimensions.sync_container_deposit_pi_accounting_dimensions',
                                        'logistics.invoice_integration.job_number_dimension_sync.sync_job_number_dimension_on_purchase_invoice_items',
                                        'logistics.invoice_integration.gl_item_dimension_sync.sync_item_accounting_dimension_from_invoice_items',
                                        'logistics.invoice_integration.container_deposit_pi_ui.validate_container_deposit_lines_have_container_before_submit'],
                      'before_update_after_submit': 'logistics.invoice_integration.gl_item_dimension_sync.sync_item_accounting_dimension_from_invoice_items',
                      'on_submit': 'logistics.invoice_integration.invoice_hooks.on_purchase_invoice_submit',
                      'on_cancel': 'logistics.invoice_integration.invoice_hooks.on_purchase_invoice_cancel'},
 'Sales Invoice': {'validate': ['logistics.invoice_integration.job_number_dimension_sync.sync_job_number_dimension_on_sales_invoice_items',
                                'logistics.invoice_integration.gl_item_dimension_sync.sync_item_accounting_dimension_from_invoice_items'],
                   'before_submit': ['logistics.invoice_integration.job_number_dimension_sync.sync_job_number_dimension_on_sales_invoice_items',
                                     'logistics.invoice_integration.gl_item_dimension_sync.sync_item_accounting_dimension_from_invoice_items'],
                   'before_update_after_submit': 'logistics.invoice_integration.gl_item_dimension_sync.sync_item_accounting_dimension_from_invoice_items',
                   'on_submit': 'logistics.invoice_integration.invoice_hooks.on_sales_invoice_submit',
                   'on_cancel': 'logistics.invoice_integration.invoice_hooks.on_sales_invoice_cancel'},
 'Journal Entry': {'before_validate': 'logistics.job_management.recognition_engine.ensure_journal_entry_posting_header',
                   'on_submit': 'logistics.invoice_integration.journal_entry_recognition_reversal.on_journal_entry_submit'},
 'Task': {'after_insert': 'logistics.integrations.outlook.task_sync.on_task_change',
          'on_update': 'logistics.integrations.outlook.task_sync.on_task_change',
          'on_trash': 'logistics.integrations.outlook.task_sync.on_task_delete'},
 'Air Booking': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                 'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                 'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                 'logistics.utils.operational_exchange_rates.on_before_save_operational_exchange_rates',
                                 'logistics.utils.linked_service_charge_parties.on_before_save_linked_service_charge_parties',
                                 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                 'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                   'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                   'logistics.utils.credit_management.on_credit_before_submit'],
                 'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                              'logistics.utils.credit_management.on_credit_validate'],
                 'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_update_after_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                            'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                 'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                 'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Air Shipment': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                  'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                  'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                  'logistics.utils.operational_exchange_rates.on_before_save_operational_exchange_rates',
                                  'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                  'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                    'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                    'logistics.utils.credit_management.on_credit_before_submit'],
                  'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                               'logistics.job_management.doc_events.on_job_validate_estimates',
                               'logistics.job_management.charge_reopen.validate_submitted_charges_not_locked',
                               'logistics.job_management.job_change_lock.validate_job_locked_against_user_edits',
                               'logistics.job_management.job_readiness.validate_job_readiness_on_status_change',
                               'logistics.utils.credit_management.on_credit_validate'],
                  'on_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                'logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle',
                                'logistics.special_projects.special_project_packages.on_freight_shipment_submit'],
                  'on_update_after_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                             'logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                             'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                  'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                  'on_cancel': ['logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                                'logistics.special_projects.special_project_packages.on_freight_shipment_cancel'],
                  'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                  'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Air Consolidation': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                       'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                       'logistics.document_management.api.update_job_document_status_on_parent_before_save'],
                       'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit'},
 'Sea Booking': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                 'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                 'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                 'logistics.utils.operational_exchange_rates.on_before_save_operational_exchange_rates',
                                 'logistics.utils.linked_service_charge_parties.on_before_save_linked_service_charge_parties',
                                 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                 'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                   'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                   'logistics.utils.credit_management.on_credit_before_submit'],
                 'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                              'logistics.utils.credit_management.on_credit_validate'],
                 'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_update_after_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                            'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                 'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                 'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Sea Shipment': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                  'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                  'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                  'logistics.utils.operational_exchange_rates.on_before_save_operational_exchange_rates',
                                  'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                  'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                    'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                    'logistics.utils.credit_management.on_credit_before_submit'],
                  'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                               'logistics.job_management.doc_events.on_job_validate_estimates',
                               'logistics.job_management.charge_reopen.validate_submitted_charges_not_locked',
                               'logistics.job_management.job_change_lock.validate_job_locked_against_user_edits',
                               'logistics.job_management.job_readiness.validate_job_readiness_on_status_change',
                               'logistics.utils.credit_management.on_credit_validate'],
                  'on_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                'logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle',
                                'logistics.special_projects.special_project_packages.on_freight_shipment_submit'],
                  'on_update_after_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                             'logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                             'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                  'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                  'on_cancel': ['logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                                'logistics.special_projects.special_project_packages.on_freight_shipment_cancel'],
                  'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                  'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Sea Consolidation': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                       'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                       'logistics.document_management.api.update_job_document_status_on_parent_before_save'],
                       'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit'},
 'Transport Order': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                     'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                     'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                     'logistics.utils.linked_service_charge_parties.on_before_save_linked_service_charge_parties',
                                     'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                     'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                       'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                       'logistics.utils.credit_management.on_credit_before_submit'],
                     'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                                  'logistics.utils.credit_management.on_credit_validate'],
                     'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                   'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                     'on_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                   'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                     'on_update_after_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                                'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                     'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                     'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                     'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Transport Job': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                   'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                   'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                   'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                   'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                     'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                     'logistics.utils.credit_management.on_credit_before_submit'],
                   'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                                'logistics.job_management.doc_events.on_job_validate_estimates',
                                'logistics.job_management.charge_reopen.validate_submitted_charges_not_locked',
                                'logistics.job_management.job_change_lock.validate_job_locked_against_user_edits',
                                'logistics.job_management.job_readiness.validate_job_readiness_on_status_change',
                                'logistics.utils.credit_management.on_credit_validate'],
                   'on_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                 'logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle',
                                 'logistics.special_projects.special_project_packages.on_transport_job_submit'],
                   'on_update_after_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                              'logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                              'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_cancel': ['logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                                 'logistics.special_projects.special_project_packages.on_transport_job_cancel'],
                   'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                   'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Declaration': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                 'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                 'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                 'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                   'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                   'logistics.utils.credit_management.on_credit_before_submit'],
                 'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                              'logistics.job_management.doc_events.on_job_validate_estimates',
                              'logistics.job_management.charge_reopen.validate_submitted_charges_not_locked',
                              'logistics.job_management.job_change_lock.validate_job_locked_against_user_edits',
                              'logistics.job_management.job_readiness.validate_job_readiness_on_status_change',
                              'logistics.utils.credit_management.on_credit_validate'],
                 'on_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                               'logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_update_after_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                            'logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                            'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                 'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                 'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Declaration Order': {'before_save': ['logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                       'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                       'logistics.utils.linked_service_charge_parties.on_before_save_linked_service_charge_parties',
                                       'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                       'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                         'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                         'logistics.utils.credit_management.on_credit_before_submit'],
                       'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                                    'logistics.utils.credit_management.on_credit_validate'],
                       'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                     'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                       'on_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                     'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                       'on_update_after_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                                  'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                       'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                       'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                       'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Inbound Order': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                   'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                   'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                   'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                   'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                     'logistics.utils.credit_management.on_credit_before_submit'],
                   'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                                'logistics.utils.credit_management.on_credit_validate'],
                   'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_update_after_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                              'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                   'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                   'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Release Order': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                   'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                   'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                   'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                   'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                     'logistics.utils.credit_management.on_credit_before_submit'],
                   'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                                'logistics.utils.credit_management.on_credit_validate'],
                   'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_update_after_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                              'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                   'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                   'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Transfer Order': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                    'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                    'logistics.document_management.api.update_job_document_status_on_parent_before_save'],
                    'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                      'logistics.utils.credit_management.on_credit_before_submit'],
                    'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
                    'validate': 'logistics.utils.credit_management.on_credit_validate'},
 'Cross-Docking Order': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                         'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                         'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                         'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                         'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                           'logistics.utils.credit_management.on_credit_before_submit'],
                         'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                                      'logistics.utils.credit_management.on_credit_validate'],
                         'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                       'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                         'on_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                       'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                         'on_update_after_submit': ['logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                                    'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                         'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                         'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                         'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Warehouse Job': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                   'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                   'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                   'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                   'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                     'logistics.warehousing.api.warehouse_job_before_submit',
                                     'logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                     'logistics.utils.credit_management.on_credit_before_submit'],
                   'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                                'logistics.job_management.doc_events.on_job_validate_estimates',
                                'logistics.job_management.charge_reopen.validate_submitted_charges_not_locked',
                                'logistics.job_management.job_change_lock.validate_job_locked_against_user_edits',
                                'logistics.job_management.job_readiness.validate_job_readiness_on_status_change',
                                'logistics.utils.credit_management.on_credit_validate'],
                   'on_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                 'logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_update_after_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                              'logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                              'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                                 'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                   'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                   'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                   'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'General Job': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                 'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                 'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                 'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                   'logistics.utils.credit_management.on_credit_before_submit'],
                 'validate': ['logistics.job_management.doc_events.on_job_validate_estimates',
                              'logistics.utils.credit_management.on_credit_validate'],
                 'on_submit': 'logistics.job_management.auto_recognition.enqueue_auto_recognize',
                 'on_update_after_submit': 'logistics.job_management.auto_recognition.enqueue_auto_recognize',
                 'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                 'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Special Project': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                     'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                     'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                     'logistics.special_projects.special_project_service_persistence.sync_special_project_services_to_documents'],
                     'before_submit': ['logistics.document_management.api.enforce_required_job_documents_before_submit',
                                       'logistics.utils.credit_management.on_credit_before_submit'],
                     'validate': ['logistics.job_management.doc_events.on_job_validate_estimates',
                                  'logistics.utils.credit_management.on_credit_validate'],
                     'on_submit': 'logistics.job_management.auto_recognition.enqueue_auto_recognize',
                     'on_update_after_submit': 'logistics.job_management.auto_recognition.enqueue_auto_recognize',
                     'on_trash': 'logistics.special_projects.special_project_service_persistence.delete_special_project_services_for_project',
                     'before_insert': 'logistics.utils.credit_management.on_credit_before_insert'},
 'Time Sensitive Case': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                         'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                         'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                         'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                         'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit',
                         'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'Project Order': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                   'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                   'logistics.document_management.api.update_job_document_status_on_parent_before_save'],
                   'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit'},
 'Project Job': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                 'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                 'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                 'logistics.utils.operational_exchange_rates.on_before_save_operational_exchange_rates',
                                 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                 'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit',
                 'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                              'logistics.job_management.doc_events.on_job_validate_estimates'],
                 'on_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                               'logistics.utils.internal_job_main_rollup.on_internal_job_submit',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_update_after_submit': ['logistics.job_management.auto_recognition.enqueue_auto_recognize',
                                            'logistics.utils.internal_job_main_rollup.on_internal_job_update_after_submit',
                                            'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_update': ['logistics.utils.internal_job_main_rollup.on_internal_job_after_save',
                               'logistics.special_projects.lifecycle_job_financial_rollup.on_operational_job_update_refresh_special_project_lifecycle'],
                 'on_cancel': 'logistics.utils.internal_job_main_rollup.on_internal_job_cancel',
                 'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'MICE Project': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                  'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                  'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                                  'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
                  'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit',
                  'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'Docket': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                            'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                            'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                            'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
            'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit',
            'validate': 'logistics.job_management.doc_events.on_job_validate_estimates',
            'on_submit': 'logistics.job_management.auto_recognition.enqueue_auto_recognize',
            'on_update_after_submit': 'logistics.job_management.auto_recognition.enqueue_auto_recognize',
            'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'MICE Order': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                                'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                                'logistics.document_management.api.update_job_document_status_on_parent_before_save'],
                'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit'},
 'MICE Job': {'before_save': ['logistics.document_management.api.ensure_documents_and_milestones_from_template',
                              'logistics.document_management.api.update_milestone_status_on_parent_before_save',
                              'logistics.document_management.api.update_job_document_status_on_parent_before_save',
                              'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs'],
              'before_submit': 'logistics.document_management.api.enforce_required_job_documents_before_submit',
              'validate': 'logistics.utils.charge_service_type.on_validate_main_service_internal_job',
              'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'VAS Order': {'validate': ['logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                            'logistics.utils.credit_management.on_credit_validate'],
               'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
               'before_submit': 'logistics.utils.credit_management.on_credit_before_submit'},
 'Exhibit Job': {'validate': 'logistics.utils.charge_service_type.on_validate_main_service_internal_job',
                 'before_save': 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs',
                 'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'Run Sheet': {'validate': 'logistics.job_management.job_change_lock.validate_job_locked_against_user_edits'},
 'Sales Quote': {'before_submit': ['logistics.customs.permit_matching.enforce_permit_alerts_before_submit',
                                   'logistics.utils.credit_management.on_credit_before_submit'],
                 'before_save': 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs',
                 'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking',
                 'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
                 'validate': 'logistics.utils.credit_management.on_credit_validate'},
 '*': {'validate': ['logistics.utils.load_type_active.validate_load_type_links_on_doc',
                    'logistics.utils.freight_agent_service.validate_freight_agent_links_on_doc']},
 'Exhibit': {'before_save': 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs',
             'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'Change Request': {'before_save': 'logistics.utils.internal_job_persistence.sync_internal_job_details_to_internal_jobs',
                    'on_trash': 'logistics.utils.internal_job_persistence.delete_internal_jobs_for_booking'},
 'Internal Job': {'on_update': 'logistics.utils.internal_job_persistence.sync_internal_job_to_detail_rows'},
 'Linked Service': {'on_update': 'logistics.utils.internal_job_persistence.sync_internal_job_to_detail_rows'},
 'Transport Consolidation Job': {'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
                                 'validate': 'logistics.utils.credit_management.on_credit_validate',
                                 'before_submit': 'logistics.utils.credit_management.on_credit_before_submit'},
 'Stocktake Order': {'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
                     'validate': 'logistics.utils.credit_management.on_credit_validate',
                     'before_submit': 'logistics.utils.credit_management.on_credit_before_submit'},
 'Gate Pass': {'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
               'validate': 'logistics.utils.credit_management.on_credit_validate',
               'before_submit': 'logistics.utils.credit_management.on_credit_before_submit'},
 'Periodic Billing': {'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
                      'validate': 'logistics.utils.credit_management.on_credit_validate',
                      'before_submit': 'logistics.utils.credit_management.on_credit_before_submit'},
 'Warehouse Contract': {'before_insert': 'logistics.utils.credit_management.on_credit_before_insert',
                        'validate': 'logistics.utils.credit_management.on_credit_validate',
                        'before_submit': 'logistics.utils.credit_management.on_credit_before_submit'}}
