# Copyright (c) 2026, Agilasoft and contributors
# For license information, please see license.txt
"""Twenty management KPI reports per workspace module.

Each row is ``(title, ref_doctype, handler_id, options_dict)`` consumed by
``logistics.analytics_reports.catalog`` and ``build_cnx_analytics_reports``.
"""
from __future__ import unicode_literals

RAW_REPORTS_BY_MODULE = {
	"Logistics": [
		('Container fleet executive control snapshot', 'Container', 'executive_snapshot', {}),
		('Container fleet weekly volume and booked value', 'Container', 'trend_weekly_value', {}),
		('Container fleet monthly volume and booked value', 'Container', 'trend_monthly_value', {}),
		('Container operational status pipeline and share', 'Container', 'pipeline_mix', {'field': 'status'}),
		('Container equipment type concentration', 'Container', 'pipeline_mix', {'field': 'container_type'}),
		('Container location type routing mix', 'Container', 'pipeline_mix', {'field': 'current_location_type'}),
		('Container return status pipeline', 'Container', 'pipeline_mix', {'field': 'return_status'}),
		('Container top locations by deposit and penalty value', 'Container', 'top_value', {'field': 'current_location', 'limit': 15}),
		('Container carrier concentration by value', 'Container', 'top_value', {'field': 'owner_carrier', 'limit': 15}),
		('Container fleet owner workload and value', 'Container', 'owner_workload', {}),
		('Container open draft aging backlog', 'Container', 'aging_open', {}),
		('Container submission health versus drafts', 'Container', 'doc_health', {}),
		('Container weekly throughput index', 'Container', 'trend_weekly_count', {}),
		('Container monthly throughput index', 'Container', 'trend_monthly_count', {}),
		('Container penalty and deposit financial exposure', 'Container', 'penalty_deposit', {}),
		('Container active versus inactive mix', 'Container', 'pipeline_mix', {'field': 'is_active'}),
		('Container master bill concentration', 'Container', 'top_value', {'field': 'master_bill', 'limit': 12}),
		('Container movement weekly activity index', 'Container Movement', 'trend_weekly_count', {}),
		('Container movement type operational mix', 'Container Movement', 'pipeline_mix', {'field': 'movement_type'}),
		('Container movement reference document concentration', 'Container Movement', 'top_value', {'field': 'reference_doctype', 'limit': 12}),
	],
	"Transport": [
		('Transport job executive control snapshot', 'Transport Job', 'executive_snapshot', {}),
		('Transport job weekly volume and value trend', 'Transport Job', 'trend_weekly_value', {}),
		('Transport job monthly volume and value trend', 'Transport Job', 'trend_monthly_value', {}),
		('Transport job SLA status pipeline mix', 'Transport Job', 'pipeline_mix', {'field': 'sla_status'}),
		('Transport job mode of transport mix', 'Transport Job', 'pipeline_mix', {'field': 'transport_mode'}),
		('Transport job vehicle type planning mix', 'Transport Job', 'pipeline_mix', {'field': 'vehicle_type'}),
		('Transport job customer value concentration', 'Transport Job', 'top_value', {'field': 'customer', 'limit': 15}),
		('Transport job carrier concentration', 'Transport Job', 'top_value', {'field': 'transport_company', 'limit': 15}),
		('Transport job branch and profit performance', 'Transport Job', 'branch_mix', {}),
		('Transport job owner workload balance', 'Transport Job', 'owner_workload', {}),
		('Transport job open draft aging backlog', 'Transport Job', 'aging_open', {}),
		('Transport job submission health ratio', 'Transport Job', 'doc_health', {}),
		('Transport job DG compliance pipeline', 'Transport Job', 'pipeline_mix', {'field': 'dg_compliance_status'}),
		('Transport job load type service mix', 'Transport Job', 'pipeline_mix', {'field': 'load_type'}),
		('Transport job project portfolio concentration', 'Transport Job', 'top_value', {'field': 'project', 'limit': 15}),
		('Transport job weekly throughput index', 'Transport Job', 'trend_weekly_count', {}),
		('Transport job monthly throughput index', 'Transport Job', 'trend_monthly_count', {}),
		('Transport job overdue and due date pressure', 'Transport Job', 'overdue_pressure', {}),
		('Transport job cost center value concentration', 'Transport Job', 'top_value', {'field': 'cost_center', 'limit': 15}),
		('Transport job profit center value concentration', 'Transport Job', 'top_value', {'field': 'profit_center', 'limit': 15}),
	],
	"Warehousing": [
		('Inbound order executive control snapshot', 'Inbound Order', 'executive_snapshot', {}),
		('Inbound weekly volume and value trend', 'Inbound Order', 'trend_weekly_value', {}),
		('Inbound monthly volume and value trend', 'Inbound Order', 'trend_monthly_value', {}),
		('Inbound customer demand concentration', 'Inbound Order', 'top_value', {'field': 'customer', 'limit': 15}),
		('Inbound priority pipeline mix', 'Inbound Order', 'pipeline_mix', {'field': 'priority'}),
		('Inbound owner workload review', 'Inbound Order', 'owner_workload', {}),
		('Inbound open draft aging backlog', 'Inbound Order', 'aging_open', {}),
		('Inbound submission health ratio', 'Inbound Order', 'doc_health', {}),
		('Inbound branch performance view', 'Inbound Order', 'branch_mix', {}),
		('Inbound overdue and due date pressure', 'Inbound Order', 'overdue_pressure', {}),
		('Release order executive control snapshot', 'Release Order', 'executive_snapshot', {}),
		('Release weekly volume and value trend', 'Release Order', 'trend_weekly_value', {}),
		('Release monthly volume and value trend', 'Release Order', 'trend_monthly_value', {}),
		('Release customer fulfillment concentration', 'Release Order', 'top_value', {'field': 'customer', 'limit': 15}),
		('Release priority pipeline mix', 'Release Order', 'pipeline_mix', {'field': 'priority'}),
		('Release owner workload review', 'Release Order', 'owner_workload', {}),
		('Release open draft aging backlog', 'Release Order', 'aging_open', {}),
		('Release submission health ratio', 'Release Order', 'doc_health', {}),
		('Release branch performance view', 'Release Order', 'branch_mix', {}),
		('Release overdue and due date pressure', 'Release Order', 'overdue_pressure', {}),
	],
	"Customs": [
		('Customs declaration executive snapshot', 'Declaration', 'executive_snapshot', {}),
		('Declaration weekly clearance volume and value', 'Declaration', 'trend_weekly_value', {}),
		('Declaration monthly clearance volume and value', 'Declaration', 'trend_monthly_value', {}),
		('Declaration status pipeline mix', 'Declaration', 'pipeline_mix', {'field': 'status'}),
		('Declaration job status pipeline mix', 'Declaration', 'pipeline_mix', {'field': 'job_status'}),
		('Declaration type regulatory mix', 'Declaration', 'pipeline_mix', {'field': 'declaration_type'}),
		('Declaration customer value concentration', 'Declaration', 'top_value', {'field': 'customer', 'limit': 15}),
		('Declaration authority workload concentration', 'Declaration', 'top_value', {'field': 'customs_authority', 'limit': 15}),
		('Declaration transport mode corridor mix', 'Declaration', 'pipeline_mix', {'field': 'transport_mode'}),
		('Declaration payment status risk pipeline', 'Declaration', 'pipeline_mix', {'field': 'payment_status'}),
		('Declaration owner workload review', 'Declaration', 'owner_workload', {}),
		('Declaration open draft aging backlog', 'Declaration', 'aging_open', {}),
		('Declaration submission health ratio', 'Declaration', 'doc_health', {}),
		('Declaration branch performance view', 'Declaration', 'branch_mix', {}),
		('Declaration weekly throughput index', 'Declaration', 'trend_weekly_count', {}),
		('Declaration monthly throughput index', 'Declaration', 'trend_monthly_count', {}),
		('Declaration overdue clearance pressure', 'Declaration', 'overdue_pressure', {}),
		('Declaration origin country trade concentration', 'Declaration', 'top_value', {'field': 'country_of_origin', 'limit': 15}),
		('Declaration destination country trade concentration', 'Declaration', 'top_value', {'field': 'country_of_destination', 'limit': 15}),
		('Declaration incoterm commercial mix', 'Declaration', 'pipeline_mix', {'field': 'incoterm'}),
	],
	"Global Customs": [
		('Global manifest executive snapshot', 'Global Manifest', 'executive_snapshot', {}),
		('Global manifest weekly filing volume', 'Global Manifest', 'trend_weekly_count', {}),
		('Global manifest monthly filing volume', 'Global Manifest', 'trend_monthly_count', {}),
		('Global manifest workflow status pipeline', 'Global Manifest', 'pipeline_mix', {'field': 'status'}),
		('Global manifest type trade lane mix', 'Global Manifest', 'pipeline_mix', {'field': 'manifest_type'}),
		('Global manifest country concentration', 'Global Manifest', 'top_value', {'field': 'country', 'limit': 15}),
		('Global manifest carrier concentration', 'Global Manifest', 'top_value', {'field': 'carrier', 'limit': 15}),
		('Global manifest branch performance view', 'Global Manifest', 'branch_mix', {}),
		('Global manifest owner workload review', 'Global Manifest', 'owner_workload', {}),
		('Global manifest open draft aging backlog', 'Global Manifest', 'aging_open', {}),
		('Global manifest submission health ratio', 'Global Manifest', 'doc_health', {}),
		('Global manifest overdue filing pressure', 'Global Manifest', 'overdue_pressure', {}),
		('Global manifest bill line weekly volume', 'Global Manifest Bill', 'trend_weekly_count', {}),
		('Global manifest bill line monthly volume', 'Global Manifest Bill', 'trend_monthly_count', {}),
		('Global manifest bill type pipeline mix', 'Global Manifest Bill', 'pipeline_mix', {'field': 'bill_type'}),
		('Global manifest bill shipper concentration', 'Global Manifest Bill', 'top_value', {'field': 'shipper', 'limit': 15}),
		('Global manifest bill consignee concentration', 'Global Manifest Bill', 'top_value', {'field': 'consignee', 'limit': 15}),
		('Global manifest bill owner workload review', 'Global Manifest Bill', 'owner_workload', {}),
		('Global manifest bill submission health ratio', 'Global Manifest Bill', 'doc_health', {}),
		('Global manifest bill package type mix', 'Global Manifest Bill', 'pipeline_mix', {'field': 'package_type'}),
	],
	"Sea Freight": [
		('Ocean shipment executive control snapshot', 'Sea Shipment', 'executive_snapshot', {}),
		('Ocean shipment weekly volume and value', 'Sea Shipment', 'trend_weekly_value', {}),
		('Ocean shipment monthly volume and value', 'Sea Shipment', 'trend_monthly_value', {}),
		('Ocean shipment shipping status pipeline', 'Sea Shipment', 'pipeline_mix', {'field': 'shipping_status'}),
		('Ocean shipment direction trade mix', 'Sea Shipment', 'pipeline_mix', {'field': 'direction'}),
		('Ocean shipment customer concentration', 'Sea Shipment', 'top_value', {'field': 'local_customer', 'limit': 15}),
		('Ocean shipment origin port concentration', 'Sea Shipment', 'top_value', {'field': 'origin_port', 'limit': 15}),
		('Ocean shipment destination port concentration', 'Sea Shipment', 'top_value', {'field': 'destination_port', 'limit': 15}),
		('Ocean shipment carrier line concentration', 'Sea Shipment', 'top_value', {'field': 'shipping_line', 'limit': 15}),
		('Ocean shipment owner workload review', 'Sea Shipment', 'owner_workload', {}),
		('Ocean shipment open draft aging backlog', 'Sea Shipment', 'aging_open', {}),
		('Ocean shipment submission health ratio', 'Sea Shipment', 'doc_health', {}),
		('Ocean shipment branch performance view', 'Sea Shipment', 'branch_mix', {}),
		('Ocean shipment overdue schedule pressure', 'Sea Shipment', 'overdue_pressure', {}),
		('Sea consolidation executive snapshot', 'Sea Consolidation', 'executive_snapshot', {}),
		('Sea consolidation weekly activity', 'Sea Consolidation', 'trend_weekly_value', {}),
		('Sea consolidation status pipeline', 'Sea Consolidation', 'pipeline_mix', {'field': 'status'}),
		('Sea consolidation type mix', 'Sea Consolidation', 'pipeline_mix', {'field': 'consolidation_type'}),
		('Sea consolidation agent concentration', 'Sea Consolidation', 'top_value', {'field': 'consolidation_agent', 'limit': 15}),
		('Sea consolidation port pair concentration', 'Sea Consolidation', 'top_value', {'field': 'origin_port', 'limit': 12}),
	],
	"Air Freight": [
		('Air shipment executive control snapshot', 'Air Shipment', 'executive_snapshot', {}),
		('Air shipment weekly volume and value', 'Air Shipment', 'trend_weekly_value', {}),
		('Air shipment monthly volume and value', 'Air Shipment', 'trend_monthly_value', {}),
		('Air shipment job status pipeline', 'Air Shipment', 'pipeline_mix', {'field': 'job_status'}),
		('Air shipment direction mix', 'Air Shipment', 'pipeline_mix', {'field': 'direction'}),
		('Air shipment customer concentration', 'Air Shipment', 'top_value', {'field': 'local_customer', 'limit': 15}),
		('Air shipment airline concentration', 'Air Shipment', 'top_value', {'field': 'airline', 'limit': 15}),
		('Air shipment origin airport concentration', 'Air Shipment', 'top_value', {'field': 'origin_port', 'limit': 15}),
		('Air shipment owner workload review', 'Air Shipment', 'owner_workload', {}),
		('Air shipment open draft aging backlog', 'Air Shipment', 'aging_open', {}),
		('Air shipment submission health ratio', 'Air Shipment', 'doc_health', {}),
		('Air shipment branch performance view', 'Air Shipment', 'branch_mix', {}),
		('Air shipment overdue schedule pressure', 'Air Shipment', 'overdue_pressure', {}),
		('Air consolidation executive snapshot', 'Air Consolidation', 'executive_snapshot', {}),
		('Air consolidation weekly activity', 'Air Consolidation', 'trend_weekly_value', {}),
		('Air consolidation status pipeline', 'Air Consolidation', 'pipeline_mix', {'field': 'status'}),
		('Air consolidation type mix', 'Air Consolidation', 'pipeline_mix', {'field': 'consolidation_type'}),
		('Air consolidation airline concentration', 'Air Consolidation', 'top_value', {'field': 'airline', 'limit': 15}),
		('Air consolidation agent concentration', 'Air Consolidation', 'top_value', {'field': 'consolidation_agent', 'limit': 15}),
		('Air consolidation weekly throughput index', 'Air Consolidation', 'trend_weekly_count', {}),
	],
	"Job Management": [
		('Job number executive snapshot', 'Job Number', 'executive_snapshot', {}),
		('Job number weekly registration index', 'Job Number', 'trend_weekly_count', {}),
		('Job number monthly registration index', 'Job Number', 'trend_monthly_count', {}),
		('Job number document type pipeline', 'Job Number', 'pipeline_mix', {'field': 'job_type'}),
		('Job number branch performance view', 'Job Number', 'branch_mix', {}),
		('Job number owner workload review', 'Job Number', 'owner_workload', {}),
		('Job number open draft aging backlog', 'Job Number', 'aging_open', {}),
		('Job number submission health ratio', 'Job Number', 'doc_health', {}),
		('Recognition policy executive snapshot', 'Recognition Policy Settings', 'executive_snapshot', {}),
		('Recognition policy weekly change index', 'Recognition Policy Settings', 'trend_weekly_count', {}),
		('Recognition policy monthly change index', 'Recognition Policy Settings', 'trend_monthly_count', {}),
		('Recognition policy enabled mix', 'Recognition Policy Settings', 'pipeline_mix', {'field': 'enabled'}),
		('Recognition policy WIP toggle mix', 'Recognition Policy Settings', 'pipeline_mix', {'field': 'enable_wip_recognition'}),
		('Recognition policy accrual toggle mix', 'Recognition Policy Settings', 'pipeline_mix', {'field': 'enable_accrual_recognition'}),
		('Recognition policy owner workload review', 'Recognition Policy Settings', 'owner_workload', {}),
		('Recognition policy open draft aging backlog', 'Recognition Policy Settings', 'aging_open', {}),
		('Recognition policy submission health ratio', 'Recognition Policy Settings', 'doc_health', {}),
		('Recognition policy company concentration', 'Recognition Policy Settings', 'top_value', {'field': 'company', 'limit': 15}),
		('Recognition policy recognition basis mix', 'Recognition Policy Settings', 'pipeline_mix', {'field': 'recognition_date_basis'}),
		('Recognition policy branch match concentration', 'Recognition Policy Settings', 'top_value', {'field': 'branch', 'limit': 15}),
	],
	"Pricing Center": [
		('Sales quote executive control snapshot', 'Sales Quote', 'executive_snapshot', {}),
		('Sales quote weekly pipeline and value', 'Sales Quote', 'trend_weekly_value', {}),
		('Sales quote monthly pipeline and value', 'Sales Quote', 'trend_monthly_value', {}),
		('Sales quote status funnel mix', 'Sales Quote', 'pipeline_mix', {'field': 'status'}),
		('Sales quote quotation type mix', 'Sales Quote', 'pipeline_mix', {'field': 'quotation_type'}),
		('Sales quote customer win concentration', 'Sales Quote', 'top_value', {'field': 'customer', 'limit': 15}),
		('Sales quote transport mode offer mix', 'Sales Quote', 'pipeline_mix', {'field': 'transport_mode'}),
		('Sales quote direction trade mix', 'Sales Quote', 'pipeline_mix', {'field': 'direction'}),
		('Sales quote owner workload review', 'Sales Quote', 'owner_workload', {}),
		('Sales quote open draft aging backlog', 'Sales Quote', 'aging_open', {}),
		('Sales quote submission health ratio', 'Sales Quote', 'doc_health', {}),
		('Sales quote branch performance view', 'Sales Quote', 'branch_mix', {}),
		('Sales quote overdue validity pressure', 'Sales Quote', 'overdue_pressure', {'due_field': 'valid_until'}),
		('Sales quote weekly throughput index', 'Sales Quote', 'trend_weekly_count', {}),
		('Sales quote monthly throughput index', 'Sales Quote', 'trend_monthly_count', {}),
		('Sales quote main service mix', 'Sales Quote', 'pipeline_mix', {'field': 'main_service'}),
		('Sales quote job type portfolio mix', 'Sales Quote', 'pipeline_mix', {'field': 'job_type'}),
		('Sales quote incoterm commercial mix', 'Sales Quote', 'pipeline_mix', {'field': 'incoterm'}),
		('Sales quote sales representative concentration', 'Sales Quote', 'top_value', {'field': 'sales_rep', 'limit': 15}),
		('Sales quote operations representative concentration', 'Sales Quote', 'top_value', {'field': 'operations_rep', 'limit': 15}),
	],
	"Sustainability": [
		('Sustainability metrics executive snapshot', 'Sustainability Metrics', 'executive_snapshot', {}),
		('Sustainability weekly environmental activity', 'Sustainability Metrics', 'trend_weekly_count', {}),
		('Sustainability monthly environmental activity', 'Sustainability Metrics', 'trend_monthly_count', {}),
		('Sustainability module source pipeline', 'Sustainability Metrics', 'pipeline_mix', {'field': 'module'}),
		('Sustainability compliance status pipeline', 'Sustainability Metrics', 'pipeline_mix', {'field': 'compliance_status'}),
		('Sustainability facility concentration', 'Sustainability Metrics', 'top_value', {'field': 'facility', 'limit': 15}),
		('Sustainability owner workload review', 'Sustainability Metrics', 'owner_workload', {}),
		('Sustainability open draft aging backlog', 'Sustainability Metrics', 'aging_open', {}),
		('Sustainability submission health ratio', 'Sustainability Metrics', 'doc_health', {}),
		('Sustainability branch performance view', 'Sustainability Metrics', 'branch_mix', {}),
		('Carbon footprint executive snapshot', 'Carbon Footprint', 'executive_snapshot', {}),
		('Carbon footprint weekly activity', 'Carbon Footprint', 'trend_weekly_count', {}),
		('Carbon footprint monthly activity', 'Carbon Footprint', 'trend_monthly_count', {}),
		('Carbon footprint emissions scope mix', 'Carbon Footprint', 'pipeline_mix', {'field': 'scope'}),
		('Carbon footprint verification pipeline', 'Carbon Footprint', 'pipeline_mix', {'field': 'verification_status'}),
		('Carbon footprint module source concentration', 'Carbon Footprint', 'top_value', {'field': 'module', 'limit': 15}),
		('Carbon footprint facility concentration', 'Carbon Footprint', 'top_value', {'field': 'facility', 'limit': 15}),
		('Carbon footprint owner workload review', 'Carbon Footprint', 'owner_workload', {}),
		('Carbon footprint submission health ratio', 'Carbon Footprint', 'doc_health', {}),
		('Carbon footprint branch performance view', 'Carbon Footprint', 'branch_mix', {}),
	],
	"Netting": [
		('Settlement entry executive snapshot', 'Settlement Entry', 'executive_snapshot', {}),
		('Settlement entry weekly netting volume', 'Settlement Entry', 'trend_weekly_value', {}),
		('Settlement entry monthly netting volume', 'Settlement Entry', 'trend_monthly_value', {}),
		('Settlement entry customer concentration', 'Settlement Entry', 'top_value', {'field': 'settlement_customer', 'limit': 15}),
		('Settlement entry supplier concentration', 'Settlement Entry', 'top_value', {'field': 'settlement_supplier', 'limit': 15}),
		('Settlement entry receivable inclusion mix', 'Settlement Entry', 'pipeline_mix', {'field': 'include_receivables'}),
		('Settlement entry payable inclusion mix', 'Settlement Entry', 'pipeline_mix', {'field': 'include_payables'}),
		('Settlement entry owner workload review', 'Settlement Entry', 'owner_workload', {}),
		('Settlement entry open draft aging backlog', 'Settlement Entry', 'aging_open', {}),
		('Settlement entry submission health ratio', 'Settlement Entry', 'doc_health', {}),
		('Settlement entry branch performance view', 'Settlement Entry', 'branch_mix', {}),
		('Settlement entry weekly throughput index', 'Settlement Entry', 'trend_weekly_count', {}),
		('Settlement group executive snapshot', 'Settlement Group', 'executive_snapshot', {}),
		('Settlement group weekly maintenance index', 'Settlement Group', 'trend_weekly_count', {}),
		('Settlement group monthly maintenance index', 'Settlement Group', 'trend_monthly_count', {}),
		('Settlement group customer concentration', 'Settlement Group', 'top_value', {'field': 'settlement_customer', 'limit': 15}),
		('Settlement group active flag pipeline', 'Settlement Group', 'pipeline_mix', {'field': 'is_active'}),
		('Settlement group owner workload review', 'Settlement Group', 'owner_workload', {}),
		('Settlement group open draft aging backlog', 'Settlement Group', 'aging_open', {}),
		('Settlement group submission health ratio', 'Settlement Group', 'doc_health', {}),
	],
	"Special Projects": [
		('Special project executive control snapshot', 'Special Project', 'executive_snapshot', {}),
		('Special project weekly delivery pulse', 'Special Project', 'trend_weekly_value', {}),
		('Special project monthly delivery pulse', 'Special Project', 'trend_monthly_value', {}),
		('Special project status portfolio pipeline', 'Special Project', 'pipeline_mix', {'field': 'status'}),
		('Special project priority risk mix', 'Special Project', 'pipeline_mix', {'field': 'priority'}),
		('Special project customer concentration', 'Special Project', 'top_value', {'field': 'customer', 'limit': 15}),
		('Special project owner workload review', 'Special Project', 'owner_workload', {}),
		('Special project open draft aging backlog', 'Special Project', 'aging_open', {}),
		('Special project submission health ratio', 'Special Project', 'doc_health', {}),
		('Special project weekly throughput index', 'Special Project', 'trend_weekly_count', {}),
		('Special project request executive snapshot', 'Special Project Request', 'executive_snapshot', {}),
		('Special project request weekly intake', 'Special Project Request', 'trend_weekly_count', {}),
		('Special project request monthly intake', 'Special Project Request', 'trend_monthly_count', {}),
		('Special project request status pipeline', 'Special Project Request', 'pipeline_mix', {'field': 'status'}),
		('Special project request priority mix', 'Special Project Request', 'pipeline_mix', {'field': 'priority'}),
		('Special project request owner workload review', 'Special Project Request', 'owner_workload', {}),
		('Special project request open draft aging backlog', 'Special Project Request', 'aging_open', {}),
		('Special project request submission health ratio', 'Special Project Request', 'doc_health', {}),
		('Special project request requested by concentration', 'Special Project Request', 'top_value', {'field': 'requested_by', 'limit': 15}),
		('Special project request overdue delivery pressure', 'Special Project Request', 'overdue_pressure', {}),
	],
	"Intercompany": [
		('Intercompany invoice log executive snapshot', 'Intercompany Invoice Log', 'executive_snapshot', {}),
		('Intercompany invoice log weekly automation volume', 'Intercompany Invoice Log', 'trend_weekly_count', {}),
		('Intercompany invoice log monthly automation volume', 'Intercompany Invoice Log', 'trend_monthly_count', {}),
		('Intercompany invoice log processing status pipeline', 'Intercompany Invoice Log', 'pipeline_mix', {'field': 'status'}),
		('Intercompany invoice log job type mix', 'Intercompany Invoice Log', 'pipeline_mix', {'field': 'job_type'}),
		('Intercompany invoice log operating company concentration', 'Intercompany Invoice Log', 'top_value', {'field': 'operating_company', 'limit': 15}),
		('Intercompany invoice log main job company concentration', 'Intercompany Invoice Log', 'top_value', {'field': 'main_job_company', 'limit': 15}),
		('Intercompany invoice log owner workload review', 'Intercompany Invoice Log', 'owner_workload', {}),
		('Intercompany invoice log submission health ratio', 'Intercompany Invoice Log', 'doc_health', {}),
		('Intercompany invoice log open draft aging backlog', 'Intercompany Invoice Log', 'aging_open', {}),
		('Intercompany sales quote executive snapshot', 'Sales Quote', 'executive_snapshot', {}),
		('Intercompany sales quote weekly quote volume', 'Sales Quote', 'trend_weekly_value', {}),
		('Intercompany sales quote monthly quote volume', 'Sales Quote', 'trend_monthly_value', {}),
		('Intercompany sales quote status funnel mix', 'Sales Quote', 'pipeline_mix', {'field': 'status'}),
		('Intercompany sales quote customer concentration', 'Sales Quote', 'top_value', {'field': 'customer', 'limit': 15}),
		('Intercompany sales quote transport mode mix', 'Sales Quote', 'pipeline_mix', {'field': 'transport_mode'}),
		('Intercompany sales quote owner workload review', 'Sales Quote', 'owner_workload', {}),
		('Intercompany sales quote open draft aging backlog', 'Sales Quote', 'aging_open', {}),
		('Intercompany sales quote submission health ratio', 'Sales Quote', 'doc_health', {}),
		('Intercompany sales quote overdue validity pressure', 'Sales Quote', 'overdue_pressure', {'due_field': 'valid_until'}),
	],
}
